import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/organism/navbar";
import Sidebar from "@/components/organism/sidebar";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-nunito-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "SIMONHAKI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunitoSans.variable} font-sans antialiased min-h-screen flex flex-col`}
      >
        <NavigationBar />

        {/* content wrapper: sidebar (fixed width) + main (flexible) */}
        <div className="flex flex-1 min-h-0">
          {/* Sidebar: beri lebar tetap dan jangan biarkan mengecil */}
          <aside className="w-[245px] flex-shrink-0">
            <Sidebar />
          </aside>

          {/* Main: ambil sisa space, gunakan min-w-0 & overflow-auto untuk scroll dan mencegah overlap */}
          <main className="flex-1 min-w-0 bg-gray-100 overflow-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
