import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/organism/navbar";
import Sidebar from "@/components/organism/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <NavigationBar />

        {/* content wrapper: sidebar (fixed width) + main (flexible) */}
        <div className="flex flex-1 min-h-0">
          {/* Sidebar: beri lebar tetap dan jangan biarkan mengecil */}
          <aside className="w-[245px] flex-shrink-0">
            <Sidebar />
          </aside>

          {/* Main: ambil sisa space, gunakan min-w-0 & overflow-auto untuk scroll dan mencegah overlap */}
          <main className="flex-1 min-w-0 bg-gray-100 overflow-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
